import { Saira } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import WhatsAppButton from "@/components/WhatsAppButton";



const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
});

export const metadata = {
  title: "Cloth Website ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${saira.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       <Navbar /> 
        {children}
      <Footer />
      <WhatsAppButton/>
      </body>
    </html>
  );
}
